language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly

notifications:
  - email: false
script:
  - julia -e 'using Pkg; Pkg.clone(pwd());'
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.build("Hecke");'
  - julia -e 'using Pkg; Pkg.test("Hecke");'
  # - travis_wait julia -e 'using Pkg; Pkg.build("Nemo")'
  # - if [ -f test/runtests.jl ]; then julia --check-bounds=yes -e 'using Pkg; Pkg.test("Nemo", coverage=true)'; fi
after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - DOCUMENTER_DEBUG=true julia -e 'using Hecke; cd(Pkg.dir("Hecke")); include(joinpath("docs", "make.jl"))'
